<?php
/**
 * EE Bored in the house.
 *
 * @category    EE
 * @package     CategoryImageAltTags
 * @author      Earl Elnar
 * @email       acenplify@gmail.com
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
$_category  = $block->getCurrentCategory();
$_imgHtml   = '';
if ($_imgUrl = $block->getImage()->getUrl($_category)) {
    $_imgHtml = '<div class="category-image"><img src="'
        . $block->escapeUrl($_imgUrl)
        . '" alt="'
        . $block->escapeHtmlAttr($_category->getEeCategoryImageAlt() ?
            $_category->getEeCategoryImageAlt() : $_category->getName())
        . '" title="'
        . $block->escapeHtmlAttr($_category->getName())
        . '" class="image" /></div>';
    $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'image');
    /* @noEscape */ echo $_imgHtml;
}
?>
